# Generated by Django 6.0.6 on 2026-07-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_business_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='business',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
