# Generated by Django 6.0.5 on 2026-06-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_category_options_alter_buyingcircle_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD — US Dollar'), ('EUR', 'EUR — Euro'), ('GBP', 'GBP — British Pound'), ('JOD', 'JOD — Jordanian Dinar'), ('SAR', 'SAR — Saudi Riyal'), ('AED', 'AED — UAE Dirham'), ('EGP', 'EGP — Egyptian Pound'), ('TRY', 'TRY — Turkish Lira')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='buyingcircle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='buyingcirclemember',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg — Kilogram'), ('g', 'g — Gram'), ('ton', 'ton — Metric Ton'), ('lb', 'lb — Pound'), ('L', 'L — Liter'), ('m', 'm — Meter'), ('m²', 'm² — Square Meter'), ('m³', 'm³ — Cubic Meter'), ('pcs', 'pcs — Pieces'), ('box', 'box — Box'), ('pallet', 'pallet — Pallet'), ('unit', 'unit — Unit')], max_length=45),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
