# Generated by Django 6.0.5 on 2026-06-30 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_product_currency_alter_buyingcircle_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyingcircle',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='min_order_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JOD', 'JOD'), ('SAR', 'SAR'), ('AED', 'AED'), ('EGP', 'EGP'), ('TRY', 'TRY')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('ton', 'ton'), ('lb', 'lb'), ('L', 'L'), ('m', 'm'), ('m²', 'm²'), ('m³', 'm³'), ('pcs', 'pcs'), ('box', 'box'), ('pallet', 'pallet'), ('unit', 'unit')], max_length=45),
        ),
    ]
